---
title: "BA_analysis"
author: "Sigrid Agersnap Bom Nielsen"
date: "18/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
pacman::p_load(tidyverse, lme4, sjmisc, lmerTest)
```

shift + control + option + M = ændr samme value flere steder i samme chunk
# Testing - ignore
```{r testing}
conditions = c('Auditory/pos', ...)
for i in range(subjects){
  d1 = data_frame()
  for j in range(conditions){
    d2 <- read_csv("data_frames/df_epochs_aud_neg0-kopi.csv")
    
    
  }
  d1 = rbind(d1,d2)
  d1$ID = i
}

?rbind

summary(d2)
```


```{r testing}

file_name = 'df_epochs_aud_neg0.csv'
data <- read_csv(paste0("data_frames/",file_name))

epochs = unique(data$epoch)

# get correct time interval, from 0 - 7 seconds
data <- data %>%
  filter(
    time < 0
    #time >= 0 & time <= 7000
  )# %>% 
  # delete first two columns by col name
  select(
    -c('...1', 'time')
  )

df = data.frame()

# for loop 
for (epoch_no in epochs){
  d = data %>% filter(epoch == epoch_no)
  
  cond = d$condition[1]
  
  d <- d %>% 
  select(
    -c(condition)
  )

  d = colMeans(d)
  d <- d %>% t() %>% data.frame
  
  d <- d %>% mutate(
  subject = str_extract(file_name, "\\d+"),
  cond = cond
  )

  df = rbind(df, d)
}


d <- d1 %>% 
  select(
    -c(condition)
  )

  )
d_test <- colMeans(d)

d_test <- d_test %>% t() %>% data.frame


test <- d_test %>% mutate(
  subject = str_extract(file_name, "\\d+")
  )

```
# the real deal

## Load data and calculate means

```{r function}
load_data <- function(file_name){
  print(file_name)
  df_temp = data.frame()
  
  data <- read_csv(paste0("data_frames/",file_name))
  
  epochs = unique(data$epoch)
  
  # get correct time interval, from 0 - 7 seconds
  data <- data %>%
    filter(
      time >= 0 & time <= 7000
    ) %>% 
    # delete first two columns by col name
    select(
      -c('...1', 'time')
  )
  
  # for loop 
  for (epoch_no in epochs){
    d = data %>% filter(epoch == epoch_no)
    
    cond = d$condition[1]
    
    d <- d %>% 
    select(
      -c(condition)
    )
  
    d = colMeans(d)
    d <- d %>% t() %>% data.frame
    
    d <- d %>% mutate(
    subject = str_extract(file_name, "\\d+"),
    cond = cond
    )

    df_temp = rbind(df_temp, d)
  }
  
  return(df_temp)
}

file_name = 'df_epochs_aud_neg0.csv'

```

```{r loop through function - df_full}
# loop through all dataframes
df = list.files(path = 'data_frames/', pattern = 'csv') %>% 
  purrr::map_df(load_data)
```

```{r rearranging cols - df_full}

df_p <- df %>% select(
  c(cond, subject)
)

df_test <- df %>% 
  select(
    -c(cond, subject)
  )

df <- cbind(df_p, df_test)

df <- df_pretty %>% 
  mutate(
    subject = as.factor(subject)
  )
```

```{r write to csv df_full}
write_csv(df, "df_full.csv")
```

## Load baseline data - to check model

```{r baseline function}

load_data_baseline <- function(file_name){
  print(file_name)
  df_temp = data.frame()
  
  data <- read_csv(paste0("data_frames/",file_name))
  
  epochs = unique(data$epoch)

  
  # get correct time interval, from 0 - 7 seconds
  data <- data %>%
    filter(
      time < 0
    )
  # saving time for later to check  
  time_stamp = mean(data$time)
  
  data <- data %>% 
    #print(time) %>% 
    # delete first two columns by col name
    select(
      -c('...1', 'time')
  )
  
  # for loop 
  for (epoch_no in epochs){
    print(file_name)
    d = data %>% filter(epoch == epoch_no)
    
    cond = d$condition[1]
    
    d <- d %>% 
    select(
      -c(condition)
    )
  
    d = colMeans(d)
    d <- d %>% t() %>% data.frame
    
    d <- d %>% mutate(
    subject = str_extract(file_name, "\\d+"),
    cond = cond,
    )

    df_temp = rbind(df_temp, d)
  }
  
  return(df_temp)
}
```

```{r loop through baseline function}
# loop through all dataframes
df_baseline = list.files(path = 'data_frames/', pattern = 'csv') %>% 
  purrr::map_df(load_data_baseline)
# tager < 10 min at køre
# check, den vælger faktisk de negative 'time' værdier..
```

```{r rearranging cols - df_baseline}

df_cs <- df_baseline %>% select(
  c(cond, subject)
)

df_no_cs <- df_baseline %>% 
  select(
    -c(cond, subject)
  )

df_baseline <- cbind(df_cs, df_no_cs)

df_baseline <- df_baseline %>% 
  mutate(
    subject = as.factor(subject)
  )
```

```{r write to csv df_baseline}
write_csv(df_baseline, "df_baseline.csv")
```

# Rearranging dataframes (H1, aud vs. vis)
## 'Real' data rearrange

```{r pivot longer}
df_long <- df %>% 
  pivot_longer(
    cols = contains('hbo') | contains ('hbr'),
    names_to = 'cha_name',
    values_to = 'theta'
  )
```

```{r make columns}
# make different columns
df_long <- df_long %>% mutate(
  chroma = ifelse(grepl('hbo',cha_name), 'hbo', 'hbr'), 
  trial = ifelse(grepl('Auditory',cond), 'aud_stim', 'vis_stim')
)
```

```{r creating ROIs}
# creating ROIs
df_long <- df_long %>% mutate(
  ROI = ifelse(
    # visual ROIs
    grepl('S15_D14', cha_name) | 
    grepl('S15_D15', cha_name) |
      
    grepl('S14_D14', cha_name) |
    grepl('S14_D13', cha_name) |
      
    grepl('S16_D14', cha_name) |
    grepl('S16_D13', cha_name) |
    grepl('S16_D15', cha_name) |
    grepl('S16_D16', cha_name) |
      
    grepl('S29_D13', cha_name) |
    grepl('S29_D16', cha_name) |
    grepl('S29_D28', cha_name) |
      
    grepl('S31_D15', cha_name) |
    grepl('S31_D16', cha_name) |
    grepl('S31_D30', cha_name) |
      
    grepl('S30_D16', cha_name) |
    grepl('S30_D28', cha_name) |
    grepl('S30_D30', cha_name) |
    grepl('S30_D29', cha_name) |
      
    grepl('S27_D28', cha_name) |
    grepl('S27_D29', cha_name) |
      
    grepl('S32_D30', cha_name) |
    grepl('S32_D29', cha_name)
  , 'vis', 'temp'),
  
  ROI = ifelse(
    # auditory ROIs
    grepl('S7_D4', cha_name) | 
    grepl('S7_D6', cha_name) |
      
    grepl('S9_D6', cha_name) |
    grepl('S9_D8', cha_name) |
    grepl('S9_D10', cha_name) |
      
    grepl('S11_D8', cha_name) |
    grepl('S11_D10', cha_name) |
    grepl('S11_D11', cha_name) |
      
    grepl('S22_D19', cha_name) |
    grepl('S22_D21', cha_name) |
    grepl('S22_D23', cha_name) |
      
    grepl('S24_D21', cha_name) |
    grepl('S24_D23', cha_name) |
    grepl('S24_D25', cha_name) |
      
    grepl('S26_D23', cha_name) |
    grepl('S26_D25', cha_name) |
    grepl('S26_D26', cha_name) |
      
    grepl('S28_D26', cha_name) |
    grepl('S28_D25', cha_name) |
    grepl('S28_D27', cha_name)
  , 'aud', ROI)
  )
```

```{r remove temp ROIs}
# removing irrelevant ROIs
df_long <- df_long %>% 
  filter(
    ROI != 'temp'
  )

# change classes
df_long <- df_long %>% 
  mutate(
    chroma = as.factor(chroma),
    trial= as.factor(trial),
    ROI = as.factor(ROI)
  )

# separate hbo and hbr
df_long_hbo <- df_long %>% 
  filter(chroma == 'hbo')

df_long_hbr <- df_long %>% 
  filter(chroma == 'hbr')
```


## BASELINE rearrange
```{r df_long_baseline}

df_long_baseline <- df_baseline %>% 
  pivot_longer(
    cols = contains('hbo') | contains ('hbr'),
    names_to = 'cha_name',
    values_to = 'theta'
  )

#make columns
# make different columns
df_long_baseline <- df_long_baseline %>% mutate(
  chroma = ifelse(grepl('hbo',cha_name), 'hbo', 'hbr'), 
  trial = ifelse(grepl('Auditory',cond), 'aud', 'vis')
)

# creating ROIs
df_long_baseline <- df_long_baseline %>% mutate(
  ROI = ifelse(
    # visual ROIs
    grepl('S15_D14', cha_name) | 
    grepl('S15_D15', cha_name) |
      
    grepl('S14_D14', cha_name) |
    grepl('S14_D13', cha_name) |
      
    grepl('S16_D14', cha_name) |
    grepl('S16_D13', cha_name) |
    grepl('S16_D15', cha_name) |
    grepl('S16_D16', cha_name) |
      
    grepl('S29_D13', cha_name) |
    grepl('S29_D16', cha_name) |
    grepl('S29_D28', cha_name) |
      
    grepl('S31_D15', cha_name) |
    grepl('S31_D16', cha_name) |
    grepl('S31_D30', cha_name) |
      
    grepl('S30_D16', cha_name) |
    grepl('S30_D28', cha_name) |
    grepl('S30_D30', cha_name) |
    grepl('S30_D29', cha_name) |
      
    grepl('S27_D28', cha_name) |
    grepl('S27_D29', cha_name) |
      
    grepl('S32_D30', cha_name) |
    grepl('S32_D29', cha_name)
  , 'vis', 'temp'),
  
  ROI = ifelse(
    # auditory ROIs
    grepl('S7_D4', cha_name) | 
    grepl('S7_D6', cha_name) |
      
    grepl('S9_D6', cha_name) |
    grepl('S9_D8', cha_name) |
    grepl('S9_D10', cha_name) |
      
    grepl('S11_D8', cha_name) |
    grepl('S11_D10', cha_name) |
    grepl('S11_D11', cha_name) |
      
    grepl('S22_D19', cha_name) |
    grepl('S22_D21', cha_name) |
    grepl('S22_D23', cha_name) |
      
    grepl('S24_D21', cha_name) |
    grepl('S24_D23', cha_name) |
    grepl('S24_D25', cha_name) |
      
    grepl('S26_D23', cha_name) |
    grepl('S26_D25', cha_name) |
    grepl('S26_D26', cha_name) |
      
    grepl('S28_D26', cha_name) |
    grepl('S28_D25', cha_name) |
    grepl('S28_D27', cha_name)
  , 'aud', ROI)
  )

# remove temp ROIs
# removing irrelevant ROIs
df_long_baseline <- df_long_baseline %>% 
  filter(
    ROI != 'temp'
  )

# change classes
df_long_baseline <- df_long_baseline %>% 
  mutate(
    chroma = as.factor(chroma),
    trial= as.factor(trial),
    ROI = as.factor(ROI)
  )

# separate hbo and hbr
df_long_baseline_hbo <- df_long_baseline %>% 
  filter(chroma == 'hbo')

df_long_baseline_hbr <- df_long_baseline %>% 
  filter(chroma == 'hbr')
```

# Building model

```{r models}
# null model
m0 <- lmer(theta ~ 1 + (1|subject) + (1|cha_name), df_long_hbo, REML = F)
#summary(m0)

m1 <- lmer(theta ~ ROI + (1|subject) + (1|cha_name), df_long_hbo, REML = F)
#summary(m1)

m2 <- lmer(theta ~ ROI + trial + (1|subject) + (1|cha_name), df_long_hbo, REML = F)
#summary(m2)

m3 <- lmer(theta ~ ROI*trial + (1|subject) + (1|cha_name), df_long_hbo, REML = F)
summary(m3)

anova(m0, m1, m2, m3)

# real model
m1 <- lmer(theta ~ 1 + trial:ROI:chroma + (1|subject), df_long_hbo, REML = F)
summary(m1)
```
## Post-hoc analysis
```{r}
# emm_options(lmerTest.limit = 10854)
# emm_options(disable.pbkrtest = TRUE)
emm_roi <- emmeans(m3, pairwise ~ ROI)
emm_roi_c <- emm_roi[[2]]
emm_trial <- emmeans(m3, pairwise ~ trial)
emm_trial_c <- emm_trial[[2]]

#Time by deviant interaction
emm_roi.trial <- emmeans(m3, pairwise ~ ROI | trial)
IC_roi.trial <- contrast(emm_roi.trial[[1]], method = "pairwise")
emm_trial.roi <- emmeans(m3, pairwise ~ trial | ROI)
IC_trial.roi <- contrast(emm_trial.roi[[1]], method = "pairwise")

# rbind(emm_rc, emm_dc, IC_r.d[1:4], IC_d.r[1:12], adjust = "mvt")
# rbind(IC_r.d[1:4], adjust = "mvt")
# rbind(IC_r.d[1:4], adjust = "none")
rbind(IC_roi.trial)
rbind(IC_trial.roi)

# IC_r.d[1:4]
# IC_d.r[1:12]
confint(rbind(IC_roi.trial))
# IC_d.r[c(1,3,7,9)]
IC_IC_trial.roi <- contrast(emm_trial.roi[[1]], interaction = c("pairwise", "consec"), by = NULL)
rbind(IC_IC_trial.roi)
confint(rbind(IC_IC_trial.roi))
```

```{r}
# trying to plot df_long_hbo

df_long_hbo %>% mutate(
    ROI_stim = ifelse(
      grepl('vis', ROI) & grepl('vis_stim', trial),
      'ROI_vis_stim_vis', 'temp'),
    
    ROI_stim = ifelse(
      grepl('vis', ROI) & grepl('aud_stim', trial),
      'ROI_vis_stim_aud', ROI_stim),
    
    ROI_stim = ifelse(
      grepl('aud', ROI) & grepl('aud_stim', trial),
      'ROI_aud_stim_aud', ROI_stim),
    
    ROI_stim = ifelse(
      grepl('aud', ROI) & grepl('vis_stim', trial),
      'ROI_aud_stim_vis', ROI_stim),
    
    ROI_stim = as_factor(ROI_stim)
) %>% 
  group_by(
    subject, ROI, trial
  ) %>% 
  ggplot() +
  aes(
    x = ROI_stim, y = theta) +
  stat_summary(
    fun = 'mean', geom = 'point', size = 2)
```


```{r}
#new try
df_long_hbr %>% 
    group_by(
  ROI, trial
  ) %>% 
  ggplot() +
  aes(
    x = ROI, y = theta, color = trial) +
  stat_summary(
    fun = 'mean', geom = 'point', size = 2) + 
    stat_summary(fun.data = "mean_se", geom = 'errorbar', width = .1) +
    stat_summary(fun = 'mean', geom = 'line', color = 'gray55', aes(group = trial)) + 
  coord_cartesian(ylim = c(-.2, 2))
```

```{r}
test <- df_long_hbr %>% filter(ROI == 'aud', trial == 'aud_stim')
test2 <- df_long_hbr %>% filter(ROI == 'aud', trial == 'vis_stim')

mean(test$theta)
mean(test2$theta)
```


```{r baseline plotting}

df_long_baseline_hbr %>% 
    group_by(
  ROI, trial
  ) %>% 
  ggplot() +
  aes(
    x = ROI, y = theta, color = trial) +
  stat_summary(
    fun = 'mean', geom = 'point', size = 2) + 
    stat_summary(fun.data = "mean_se", geom = 'errorbar', width = .1) +
    stat_summary(fun = 'mean', geom = 'line', color = 'gray55', aes(group = trial))+ 
  coord_cartesian(ylim = c(-.2, 2))


```



```{r}
df_long_2  %>% 
  group_by(sent_type) %>% 
  ggplot() +
  aes(x = subsection, y = sent_score, color = sent_type) +
  stat_summary(fun = 'mean', geom = 'point', size = 1) +
  stat_summary(fun.data = "mean_se", geom = 'errorbar', width = .1) +
  labs(
    title = 'Sentiment compound score of text and headline of articles',
    subtitle = 'Articles from New York Times (1st of January - 15th of September 2021)',
    x = '', 
    y = 'Compound score',
    color = '') +
  scale_color_manual(labels = c('Headline','Mean', 'Text'), values = c('red', 'grey40','blue')) +
  geom_hline(
    yintercept = -.21, 
    alpha = .4, linetype = 'dashed'
  ) + 
  coord_cartesian(ylim = c(-1,1)) #+
  #geom_text(aes(x = factor('Middle East'), y = -.10, label = 'mean'), size = 3)
  
```


```{r models}
# baseline model
m2 <- lmer(theta ~ 1 + trial:ROI:chroma + (1|subject), df_long_baseline, REML = F)

summary(m1)
summary(m2)
```

```{r checking assumptions}
# checking assumptions with diagnostic plots
qqnorm(resid(m3))
plot(m3)

qqnorm(resid(m2))
plot(m2)
```

# Pos vis/aud versus neg vis/aud - whole brain

```{r df_long2}
# FOR H3 
# remove 'neu'
df_long2 <- df_long %>% filter(
  grepl('pos', cond) | grepl('neg', cond))


```

